### ISSUE TITLE
Image Tagger

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#79]
Upload batch of pre filtered images that show up in concepts. 
Next features:
Images have obscurity 
Image queue
Integrate images search

**Comment by OLI9292** [comment]
/image/:id  view

image at top

underneath:
caption
date
author
url
permission  ["creative commons", "labeled for reuse"]
sourceUrl
words
quality
obscurity

during enrichment
	should be mobile friendly
	add progress bar
	user can go back and next
	default delete image and word relationships if user doesn't "keep"
	hide unessential data (everything except caption, words, quality obscurity)

**Comment by OLI9292** [comment]
### Tasks

- [ ] batch upload route (create images, word relationships, queue)
- [ ] edit image view
- [ ] queue functionality
- [ ] helper text for upload
