### ISSUE TITLE
[DEMO / IMPORTANT] Rob "Enhanced" Data

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#99]
## Issue

We want to show Rob improvements on our software and capabilities, without giving away too much.  With the map PR and audio tour close to done, K/V pairs deployed, we should be able to give a slick demo, with a small amount of data collection.

### Tasks

- [ ] obtain geocoded addresses, k / v pairs, passages (?) for 5 - 10 locations in an area of Manhattan (gramercy park?)
- [ ] deploy map PR
- [ ] Rob's `/concept/:id` view
- [ ] wavenet audio and test Swift audio tour

@bencbernstein @cashmonides with an agreement on this direction and it's output, this should be achievable with ~2 days work
